/* AUTO-GENERATED by spangap-inside. Do not edit; regenerated each build.
 * Transitive browser registration — the browser-half parallel to the
 * firmware's generated boot registration. Every staged straddle that
 * declares browser_register: has its UI registered here, in init order. The
 * buildable loads this ONCE from boot/modules.ts:
 *   import registerStraddles from './straddles.gen'
 *   ... registerStraddles()
 * Staging a browser_register straddle is enough to surface its pane — no
 * edit here, no modules.ts edit. `when:`-gated hooks appear only when
 * their gating straddle is staged. GENERATED_PANELS holds the declarative
 * `settings:` descriptors, rendered at runtime by GeneratedPanel.vue;
 * APP_ICONS are the launcher SVGs bundled for the bottom Dock. */
import { registerRnsd } from 'rns/modules/rnsd'
import { registerLxmf } from 'lxmf/modules/lxmf'
import { registerAppIcons } from 'spangap-browser/lib/apps'

const APP_ICONS = import.meta.glob('../app-icons/*.svg', { query: '?raw', import: 'default', eager: true }) as Record<string, string>

export default function registerStraddles(): void {
  registerAppIcons(APP_ICONS)
  registerRnsd()
  registerLxmf()
}
